version: '3.4'

services:
  productdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce


  satoshiapp.productapi:
    image: ${DOCKER_REGISTRY-}satoshiappproductapi
    build:
      context: .
      dockerfile: APIs/ProductApi/SatoshiApp.ProductApi/Dockerfile

  satoshiapp.basketapi:
    image: ${DOCKER_REGISTRY-}satoshiappbasketapi
    build:
      context: .
      dockerfile: APIs/BasketApi/Satoshiapp.BasketApi/Dockerfile

  satoshiapp.discountapi:
    image: ${DOCKER_REGISTRY-}satoshiappdiscountapi
    build:
      context: .
      dockerfile: APIs/DiscountApi/SatoshiApp.DiscountApi/Dockerfile

  satoshiapp.discountgrpc:
    image: ${DOCKER_REGISTRY-}satoshiappdiscountgrpc
    build:
      context: .
      dockerfile: APIs/DiscountApi/SatoshiApp.DiscountGrpc/Dockerfile

  satoshiapp.orderapi:
    image: ${DOCKER_REGISTRY-}satoshiapporderapi
    build:
      context: .
      dockerfile: APIs/OrderApi/SatoshiApp.OrderApi/Dockerfile

  satoshi.apigateway:
    image: ${DOCKER_REGISTRY-}satoshiapigateway
    build:
      context: .
      dockerfile: APIGateway/Satoshi.ApiGateway/Dockerfile

  satoshiapp.aggregator:
    image: ${DOCKER_REGISTRY-}satoshiappaggregator
    build:
      context: .
      dockerfile: APIGateway/SatoshiApp.Aggregator/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: