version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db 

  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Discountdb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "YEso!@12"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=somad@yessoufou.com
        - PGADMIN_DEFAULT_PASSWORD=Admin@123
    restart: always
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "8080:8000"
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  satoshiapp.productapi:
    container_name: satoshiapp.productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productdb:27017"
    depends_on:
      - productdb
    ports:
      - "9001:80"

  satoshiapp.basketapi:
    container_name: satoshiapp.basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@localhost:5672"
    depends_on:
        - basketdb
        - rabbitmq
    ports:
      - "9002:80"

  satoshiapp.discountapi:
    container_name: satoshiapp.discountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=Discountdb;User Id=admin;Password=admin1234;"
    depends_on:
        - discountdb
    ports:
      - "9003:80"

  satoshiapp.discountgrpc:
    container_name: satoshiapp.discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=localhost;Port=5432;Database=Discountdb;User Id=admin;Password=admin1234;"
    depends_on:
        - discountdb
    ports:
      - "9004:80"

  satoshiapp.orderapi:
    container_name: satoshiapp.orderapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=codelearnersoft.net;Database=SatoshiDB;User ID=sa;Password=YEso!@12;Trusted_Connection=False;MultipleActiveResultSets=true;TrustServerCertificate=True"
      - "EventBusSettings:HostAddress=amqp://guest:guest@localhost:5672"
    depends_on:
        - orderdb
        - rabbitmq
    ports:
      - "9005:80"

  satoshi.apigateway:
    container_name: satoshi.apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - satoshiapp.productapi
        - satoshiapp.basketapi
        - satoshiapp.discountapi
        - satoshiapp.orderapi
    ports:
      - "9006:80"

  satoshiapp.aggregator:
    container_name: satoshiapp.aggregator
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ApiSettings:ProductUrl=http://satoshiapp.productapi"
        - "ApiSettings:BasketUrl=http://satoshiapp.basketapi"
        - "ApiSettings:OrderUrl=http://satoshiapp.orderapi"
    depends_on:
        - satoshiapp.productapi
        - satoshiapp.basketapi
        - satoshiapp.orderapi
    ports:
        - "9007:80"
