version: '3.4'

services:
  satoshiapp.userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  satoshiapp.productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  satoshiapp.customer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  satoshiapp.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

