version: '3.4'

services:
  productdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce


  satoshiapp.productapi:
    image: ${DOCKER_REGISTRY-}satoshiappproductapi
    build:
      context: .
      dockerfile: APIs/ProductApi/SatoshiApp.ProductApi/Dockerfile

  satoshiapp.basketapi:
    image: ${DOCKER_REGISTRY-}satoshiappbasketapi
    build:
      context: .
      dockerfile: APIs/BasketApi/Satoshiapp.BasketApi/Dockerfile

  satoshiapp.discountapi:
    image: ${DOCKER_REGISTRY-}satoshiappdiscountapi
    build:
      context: .
      dockerfile: APIs/DiscountApi/SatoshiApp.DiscountApi/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: